### ISSUE TITLE
Could you offer the baseline implement of one-sided B+ tree?

### ISSUE THREAD

**Issue by furtheranddeeper** [SJTU-IPADS/xstore#2]
I am interested in the huge performance gap between XStore and one-sided B+ tree( XStore is even superior to all-cached B+tree).
Can you offer the baseline B+ tree code for reproduction?

**Comment by wxdwfc** [comment]
XStore is never compared with an "all-cached" BTree: it only compares with a setup that caches all the internal nodes above the leaves.

**Comment by furtheranddeeper** [comment]
Sorry, my expression is incorrect.
So, can I find "a setup that caches all the internal nodes above the leaves" in the xstore-legacy repo?
If not , where can I get the "setup BTree" for reproduction?

**Comment by wxdwfc** [comment]
Hi, we don't intend to open source the BTree. If you want to the related code, please drop me an email (wxdwfc@sjtu.edu.cn) so I can send you a private tarball.
