### ISSUE TITLE
compile error when make fserver

### ISSUE THREAD

**Issue by furtheranddeeper** [SJTU-IPADS/xstore#3]
I have installed mkl, modify the build-toml, generate CMakeList.txt, make jemalloc and boost successfully,
but when do "make fserver", the terminal report errors like below.
Does it occur because of disable intel RTM?
How can I check the reason and re-enable it?
---------------------------------------------------------------------------------------------------------
root@fs232:/home/wty/xstore-legacy# make fserver
Scanning dependencies of target gflags_nothreads_static
[  5%] Building CXX object deps/ggflags/CMakeFiles/gflags_nothreads_static.dir/src/gflags.cc.o
[ 10%] Building CXX object deps/ggflags/CMakeFiles/gflags_nothreads_static.dir/src/gflags_reporting.cc.o
[ 10%] Building CXX object deps/ggflags/CMakeFiles/gflags_nothreads_static.dir/src/gflags_completions.cc.o
[ 15%] Linking CXX static library libgflags_nothreads.a
[ 15%] Built target gflags_nothreads_static
[ 45%] Built target boost
[ 75%] Built target jemalloc
Scanning dependencies of target fserver
[ 80%] Building CXX object CMakeFiles/fserver.dir/server/main.cc.o
In file included from /home/wty/xstore-legacy/server/config.hpp:3:0,
                 from /home/wty/xstore-legacy/server/main.cc:3:
/home/wty/xstore-legacy/src/common.hpp:16:32: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-W#warnings"
                                ^~~~~~~~~~~~~
In file included from /home/wty/xstore-legacy/src/stores/naive_tree.hpp:8:0,
                 from /home/wty/xstore-legacy/src/stores/mod.hpp:3,
                 from /home/wty/xstore-legacy/server/controler/../internal/table.hpp:6,
                 from /home/wty/xstore-legacy/server/controler/../internal/tables.hpp:3,
                 from /home/wty/xstore-legacy/server/controler/handlers.hpp:8,
                 from /home/wty/xstore-legacy/server/startup.hpp:8,
                 from /home/wty/xstore-legacy/server/worker.hpp:14,
                 from /home/wty/xstore-legacy/server/main.cc:6:
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp: In constructor ‘fstore::utils::RTMScope<MAX_NESTED, MAX_CAPACITY, MAX_CONFLICT>::RTMScope(fstore::utils::SpinLock*)’:
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:25:23: error: there are no arguments to ‘_xbegin’ that depend on a template parameter, so a declaration of ‘_xbegin’ must be available [-fpermissive]
       unsigned stat = _xbegin();
                       ^~~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:25:23: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:27:18: error: ‘_XBEGIN_STARTED’ was not declared in this scope
       if(stat == _XBEGIN_STARTED) {
                  ^~~~~~~~~~~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:31:11: error: there are no arguments to ‘_xabort’ that depend on a template parameter, so a declaration of ‘_xabort’ must be available [-fpermissive]
           _xabort(fallback_abort_flag);
           ^~~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:34:20: error: ‘_XABORT_NESTED’ was not declared in this scope
         if((stat & _XABORT_NESTED) != 0)
                    ^~~~~~~~~~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:34:20: note: suggested alternative: ‘MAX_NESTED’
         if((stat & _XABORT_NESTED) != 0)
                    ^~~~~~~~~~~~~~
                    MAX_NESTED
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:38:25: error: ‘_XABORT_CONFLICT’ was not declared in this scope
         else if((stat & _XABORT_CONFLICT) != 0) {
                         ^~~~~~~~~~~~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:38:25: note: suggested alternative: ‘MAX_CONFLICT’
         else if((stat & _XABORT_CONFLICT) != 0) {
                         ^~~~~~~~~~~~~~~~
                         MAX_CONFLICT
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:41:25: error: ‘_XABORT_CAPACITY’ was not declared in this scope
         else if((stat & _XABORT_CAPACITY) != 0)
                         ^~~~~~~~~~~~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:41:25: note: suggested alternative: ‘MAX_CAPACITY’
         else if((stat & _XABORT_CAPACITY) != 0)
                         ^~~~~~~~~~~~~~~~
                         MAX_CAPACITY
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:43:21: error: ‘_XABORT_EXPLICIT’ was not declared in this scope
         if ((stat & _XABORT_EXPLICIT) && _XABORT_CODE(stat) == fallback_abort_flag) {
                     ^~~~~~~~~~~~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:43:42: error: there are no arguments to ‘_XABORT_CODE’ that depend on a template parameter, so a declaration of ‘_XABORT_CODE’ must be available [-fpermissive]
         if ((stat & _XABORT_EXPLICIT) && _XABORT_CODE(stat) == fallback_abort_flag) {
                                          ^~~~~~~~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:45:13: error: there are no arguments to ‘_mm_pause’ that depend on a template parameter, so a declaration of ‘_mm_pause’ must be available [-fpermissive]
             _mm_pause();
             ^~~~~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp: In destructor ‘fstore::utils::RTMScope<MAX_NESTED, MAX_CAPACITY, MAX_CONFLICT>::~RTMScope()’:
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:66:7: error: there are no arguments to ‘_xend’ that depend on a template parameter, so a declaration of ‘_xend’ must be available [-fpermissive]
       _xend();
       ^~~~~

**Comment by wxdwfc** [comment]
RTM should be supported.  It is enabled by default for recent generations of Intel server CPUs.

**Comment by furtheranddeeper** [comment]
Thanks for your reply. My CPU info paste below.
------------------------------------------ 
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              88
On-line CPU(s) list: 0-87
Thread(s) per core:  2
Core(s) per socket:  22
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6161 CPU @ 2.20GHz
Stepping:            4
CPU MHz:             1000.123
CPU max MHz:         2201.0000
CPU min MHz:         1000.0000

Supposed RTM configuration was ok, what is the real reason for compile error below(I pasted all the error message in terminal)?
-----------------------------------------------------------------------
root@fs232:/home/wty/xstore-legacy# make fserver
Scanning dependencies of target gflags_nothreads_static
[  5%] Building CXX object deps/ggflags/CMakeFiles/gflags_nothreads_static.dir/src/gflags.cc.o
[ 10%] Building CXX object deps/ggflags/CMakeFiles/gflags_nothreads_static.dir/src/gflags_reporting.cc.o
[ 10%] Building CXX object deps/ggflags/CMakeFiles/gflags_nothreads_static.dir/src/gflags_completions.cc.o
[ 15%] Linking CXX static library libgflags_nothreads.a
[ 15%] Built target gflags_nothreads_static
[ 45%] Built target boost
[ 75%] Built target jemalloc
Scanning dependencies of target fserver
[ 80%] Building CXX object CMakeFiles/fserver.dir/server/main.cc.o
In file included from /home/wty/xstore-legacy/server/config.hpp:3:0,
                 from /home/wty/xstore-legacy/server/main.cc:3:
/home/wty/xstore-legacy/src/common.hpp:16:32: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-W#warnings"
                                ^~~~~~~~~~~~~
In file included from /home/wty/xstore-legacy/src/stores/naive_tree.hpp:8:0,
                 from /home/wty/xstore-legacy/src/stores/mod.hpp:3,
                 from /home/wty/xstore-legacy/server/controler/../internal/table.hpp:6,
                 from /home/wty/xstore-legacy/server/controler/../internal/tables.hpp:3,
                 from /home/wty/xstore-legacy/server/controler/handlers.hpp:8,
                 from /home/wty/xstore-legacy/server/startup.hpp:8,
                 from /home/wty/xstore-legacy/server/worker.hpp:14,
                 from /home/wty/xstore-legacy/server/main.cc:6:
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp: In constructor ‘fstore::utils::RTMScope<MAX_NESTED, MAX_CAPACITY, MAX_CONFLICT>::RTMScope(fstore::utils::SpinLock*)’:
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:25:23: error: there are no arguments to ‘_xbegin’ that depend on a template parameter, so a declaration of ‘_xbegin’ must be available [-fpermissive]
       unsigned stat = _xbegin();
                       ^~~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:25:23: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:27:18: error: ‘_XBEGIN_STARTED’ was not declared in this scope
       if(stat == _XBEGIN_STARTED) {
                  ^~~~~~~~~~~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:31:11: error: there are no arguments to ‘_xabort’ that depend on a template parameter, so a declaration of ‘_xabort’ must be available [-fpermissive]
           _xabort(fallback_abort_flag);
           ^~~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:34:20: error: ‘_XABORT_NESTED’ was not declared in this scope
         if((stat & _XABORT_NESTED) != 0)
                    ^~~~~~~~~~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:34:20: note: suggested alternative: ‘MAX_NESTED’
         if((stat & _XABORT_NESTED) != 0)
                    ^~~~~~~~~~~~~~
                    MAX_NESTED
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:38:25: error: ‘_XABORT_CONFLICT’ was not declared in this scope
         else if((stat & _XABORT_CONFLICT) != 0) {
                         ^~~~~~~~~~~~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:38:25: note: suggested alternative: ‘MAX_CONFLICT’
         else if((stat & _XABORT_CONFLICT) != 0) {
                         ^~~~~~~~~~~~~~~~
                         MAX_CONFLICT
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:41:25: error: ‘_XABORT_CAPACITY’ was not declared in this scope
         else if((stat & _XABORT_CAPACITY) != 0)
                         ^~~~~~~~~~~~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:41:25: note: suggested alternative: ‘MAX_CAPACITY’
         else if((stat & _XABORT_CAPACITY) != 0)
                         ^~~~~~~~~~~~~~~~
                         MAX_CAPACITY
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:43:21: error: ‘_XABORT_EXPLICIT’ was not declared in this scope
         if ((stat & _XABORT_EXPLICIT) && _XABORT_CODE(stat) == fallback_abort_flag) {
                     ^~~~~~~~~~~~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:43:42: error: there are no arguments to ‘_XABORT_CODE’ that depend on a template parameter, so a declaration of ‘_XABORT_CODE’ must be available [-fpermissive]
         if ((stat & _XABORT_EXPLICIT) && _XABORT_CODE(stat) == fallback_abort_flag) {
                                          ^~~~~~~~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:45:13: error: there are no arguments to ‘_mm_pause’ that depend on a template parameter, so a declaration of ‘_mm_pause’ must be available [-fpermissive]
             _mm_pause();
             ^~~~~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp: In destructor ‘fstore::utils::RTMScope<MAX_NESTED, MAX_CAPACITY, MAX_CONFLICT>::~RTMScope()’:
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:66:7: error: there are no arguments to ‘_xend’ that depend on a template parameter, so a declaration of ‘_xend’ must be available [-fpermissive]
       _xend();
       ^~~~~
In file included from /home/wty/xstore-legacy/src/stores/naive_tree.hpp:6:0,
                 from /home/wty/xstore-legacy/src/stores/mod.hpp:3,
                 from /home/wty/xstore-legacy/server/controler/../internal/table.hpp:6,
                 from /home/wty/xstore-legacy/server/controler/../internal/tables.hpp:3,
                 from /home/wty/xstore-legacy/server/controler/handlers.hpp:8,
                 from /home/wty/xstore-legacy/server/startup.hpp:8,
                 from /home/wty/xstore-legacy/server/worker.hpp:14,
                 from /home/wty/xstore-legacy/server/main.cc:6:
/home/wty/xstore-legacy/src/stores/node.hpp: In instantiation of ‘struct fstore::store::LeafNode<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager>’:
/home/wty/xstore-legacy/server/controler/../internal/xcache_learner.hh:151:32:   required from here
/home/wty/xstore-legacy/src/stores/node.hpp:33:16: warning: ignoring packed attribute because of unpacked non-POD field ‘fstore::OpaqueData<8> fstore::store::LeafNode<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager>::values [16]’
   VAL values[IM];
                ^
In file included from /home/wty/xstore-legacy/server/controler/all.hpp:4:0,
                 from /home/wty/xstore-legacy/server/worker.hpp:16,
                 from /home/wty/xstore-legacy/server/main.cc:6:
/home/wty/xstore-legacy/server/controler/control_handlers.hpp: In static member function ‘static void fstore::server::ControlHandlers::meta_server(r2::rpc::RPC&, const r2::rpc::Req::Meta&, const char*, fstore::u32)’:
/home/wty/xstore-legacy/server/controler/control_handlers.hpp:46:5: warning: narrowing conversion of ‘fstore::server::fLI64::FLAGS_threads’ from ‘gflags::int64 {aka long int}’ to ‘fstore::u64 {aka long unsigned int}’ inside { } [-Wnarrowing]
     };
     ^
In file included from /home/wty/xstore-legacy/server/controler/all.hpp:5:0,
                 from /home/wty/xstore-legacy/server/worker.hpp:16,
                 from /home/wty/xstore-legacy/server/main.cc:6:
/home/wty/xstore-legacy/server/controler/lidx_handler.hpp: In static member function ‘static void fstore::server::LRHandlers::xcache_meta(r2::rpc::RPC&, const r2::rpc::Req::Meta&, const char*, fstore::u32)’:
/home/wty/xstore-legacy/server/controler/lidx_handler.hpp:69:50: warning: narrowing conversion of ‘tab.fstore::server::Table::xcache->fstore::XCache<fstore::LRModel<>, fstore::SubModel<fstore::LRModel<>, fstore::store::BPageStream<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager>, fstore::store::NaiveTree<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager> > >::sub_models.std::vector<fstore::SubModel<fstore::LRModel<>, fstore::store::BPageStream<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager>, fstore::store::NaiveTree<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager> >, std::allocator<fstore::SubModel<fstore::LRModel<>, fstore::store::BPageStream<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager>, fstore::store::NaiveTree<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager> > > >::size()’ from ‘std::vector<fstore::SubModel<fstore::LRModel<>, fstore::store::BPageStream<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager>, fstore::store::NaiveTree<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager> >, std::allocator<fstore::SubModel<fstore::LRModel<>, fstore::store::BPageStream<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager>, fstore::store::NaiveTree<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager> > > >::size_type {aka long unsigned int}’ to ‘fstore::u32 {aka unsigned int}’ inside { } [-Wnarrowing]
       .num_submodel = tab.xcache->sub_models.size(),
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/home/wty/xstore-legacy/server/controler/lidx_handler.hpp: In static member function ‘static void fstore::server::LRHandlers::model_meta(r2::rpc::RPC&, const r2::rpc::Req::Meta&, const char*, fstore::u32)’:
/home/wty/xstore-legacy/server/controler/lidx_handler.hpp:121:30: warning: narrowing conversion of ‘tab.fstore::server::Table::data.fstore::store::NaiveTree<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager>::depth’ from ‘int’ to ‘fstore::u64 {aka long unsigned int}’ inside { } [-Wnarrowing]
       .tree_depth = tab.data.depth
                     ~~~~~~~~~^~~~~
In file included from /home/wty/xstore-legacy/src/xcache/mod.hh:28:0,
                 from /home/wty/xstore-legacy/server/controler/../internal/table.hpp:15,
                 from /home/wty/xstore-legacy/server/controler/../internal/tables.hpp:3,
                 from /home/wty/xstore-legacy/server/controler/handlers.hpp:8,
                 from /home/wty/xstore-legacy/server/startup.hpp:8,
                 from /home/wty/xstore-legacy/server/worker.hpp:14,
                 from /home/wty/xstore-legacy/server/main.cc:6:
/home/wty/xstore-legacy/src/xcache/./seralize.hh: In instantiation of ‘static void fstore::Serializer::serialize_submodel(S&, char*) [with S = fstore::SubModel<fstore::LRModel<>, fstore::store::BPageStream<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager>, fstore::store::NaiveTree<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager> >]’:
/home/wty/xstore-legacy/server/controler/../internal/xcache_learner.hh:97:51:   required from here
/home/wty/xstore-legacy/src/xcache/./seralize.hh:92:15: warning: narrowing conversion of ‘model.fstore::SubModel<fstore::LRModel<>, fstore::store::BPageStream<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager>, fstore::store::NaiveTree<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager> >::page_table.std::vector<long unsigned int>::size()’ from ‘std::vector<long unsigned int>::size_type {aka long unsigned int}’ to ‘fstore::u32 {aka unsigned int}’ inside { } [-Wnarrowing]
     SubHeader header{ .page_entries =
               ^~~~~~
/home/wty/xstore-legacy/src/xcache/./seralize.hh:92:15: warning: narrowing conversion of ‘buf.std::__cxx11::basic_string<char>::size()’ from ‘std::__cxx11::basic_string<char>::size_type {aka long unsigned int}’ to ‘fstore::u32 {aka unsigned int}’ inside { } [-Wnarrowing]
/home/wty/xstore-legacy/src/xcache/./seralize.hh:104:42: warning: narrowing conversion of ‘model.fstore::SubModel<fstore::LRModel<>, fstore::store::BPageStream<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager>, fstore::store::NaiveTree<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager> >::train_watermark’ from ‘fstore::u64 {aka long unsigned int}’ to ‘fstore::u32 {aka unsigned int}’ inside { } [-Wnarrowing]
                       .train_seq = model.train_watermark
                                    ~~~~~~^~~~~~~~~~~~~~~
/home/wty/xstore-legacy/src/xcache/./seralize.hh: In instantiation of ‘static fstore::usize fstore::Serializer::direct_serialize(S&, char*) [with S = fstore::SubModel<fstore::LRModel<>, fstore::store::BPageStream<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager>, fstore::store::NaiveTree<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager> >; fstore::usize = unsigned int]’:
/home/wty/xstore-legacy/server/controler/handlers.hpp:181:70:   required from here
/home/wty/xstore-legacy/src/xcache/./seralize.hh:34:15: warning: narrowing conversion of ‘model.fstore::SubModel<fstore::LRModel<>, fstore::store::BPageStream<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager>, fstore::store::NaiveTree<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager> >::page_table.std::vector<long unsigned int>::size()’ from ‘std::vector<long unsigned int>::size_type {aka long unsigned int}’ to ‘fstore::u32 {aka unsigned int}’ inside { } [-Wnarrowing]
     SubHeader header
               ^~~~~~
/home/wty/xstore-legacy/src/xcache/./seralize.hh:34:15: warning: narrowing conversion of ‘buf.std::__cxx11::basic_string<char>::size()’ from ‘std::__cxx11::basic_string<char>::size_type {aka long unsigned int}’ to ‘fstore::u32 {aka unsigned int}’ inside { } [-Wnarrowing]
/home/wty/xstore-legacy/src/xcache/./seralize.hh:48:26: warning: narrowing conversion of ‘model.fstore::SubModel<fstore::LRModel<>, fstore::store::BPageStream<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager>, fstore::store::NaiveTree<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager> >::train_watermark’ from ‘fstore::u64 {aka long unsigned int}’ to ‘fstore::u32 {aka unsigned int}’ inside { } [-Wnarrowing]
       .train_seq = model.train_watermark
                    ~~~~~~^~~~~~~~~~~~~~~
In file included from /home/wty/xstore-legacy/src/stores/naive_tree.hpp:8:0,
                 from /home/wty/xstore-legacy/src/stores/mod.hpp:3,
                 from /home/wty/xstore-legacy/server/controler/../internal/table.hpp:6,
                 from /home/wty/xstore-legacy/server/controler/../internal/tables.hpp:3,
                 from /home/wty/xstore-legacy/server/controler/handlers.hpp:8,
                 from /home/wty/xstore-legacy/server/startup.hpp:8,
                 from /home/wty/xstore-legacy/server/worker.hpp:14,
                 from /home/wty/xstore-legacy/server/main.cc:6:
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp: In instantiation of ‘fstore::utils::RTMScope<MAX_NESTED, MAX_CAPACITY, MAX_CONFLICT>::RTMScope(fstore::utils::SpinLock*) [with int MAX_NESTED = 0; int MAX_CAPACITY = 1; int MAX_CONFLICT = 100]’:
/home/wty/xstore-legacy/src/stores/naive_tree.hpp:183:23:   required from ‘std::pair<VAL*, std::experimental::fundamentals_v1::optional<std::pair<_FIter, _FIter> > > fstore::store::NaiveTree<KEY, VAL, P>::safe_get_with_insert_check_split(fstore::u64) [with KEY = long unsigned int; VAL = fstore::OpaqueData<8>; P = fstore::BlockPager; fstore::u64 = long unsigned int]’
/home/wty/xstore-legacy/server/controler/handlers.hpp:372:67:   required from here
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:25:30: error: ‘_xbegin’ was not declared in this scope
       unsigned stat = _xbegin();
                       ~~~~~~~^~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:31:18: error: ‘_xabort’ was not declared in this scope
           _xabort(fallback_abort_flag);
           ~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:31:18: note: suggested alternative: ‘abort’
           _xabort(fallback_abort_flag);
           ~~~~~~~^~~~~~~~~~~~~~~~~~~~~
           abort
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:43:54: error: ‘_XABORT_CODE’ was not declared in this scope
         if ((stat & _XABORT_EXPLICIT) && _XABORT_CODE(stat) == fallback_abort_flag) {
                                          ~~~~~~~~~~~~^~~~~~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:45:22: error: ‘_mm_pause’ was not declared in this scope
             _mm_pause();
             ~~~~~~~~~^~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:45:22: note: suggested alternative: ‘pause’
             _mm_pause();
             ~~~~~~~~~^~
             pause
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp: In instantiation of ‘fstore::utils::RTMScope<MAX_NESTED, MAX_CAPACITY, MAX_CONFLICT>::~RTMScope() [with int MAX_NESTED = 0; int MAX_CAPACITY = 1; int MAX_CONFLICT = 100]’:
/home/wty/xstore-legacy/src/stores/naive_tree.hpp:183:23:   required from ‘std::pair<VAL*, std::experimental::fundamentals_v1::optional<std::pair<_FIter, _FIter> > > fstore::store::NaiveTree<KEY, VAL, P>::safe_get_with_insert_check_split(fstore::u64) [with KEY = long unsigned int; VAL = fstore::OpaqueData<8>; P = fstore::BlockPager; fstore::u64 = long unsigned int]’
/home/wty/xstore-legacy/server/controler/handlers.hpp:372:67:   required from here
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:66:12: error: ‘_xend’ was not declared in this scope
       _xend();
       ~~~~~^~
/home/wty/xstore-legacy/src/stores/../utils/rtm_scope.hpp:66:12: note: suggested alternative: ‘send’
       _xend();
       ~~~~~^~
       send
In file included from /home/wty/xstore-legacy/src/model_config.hpp:4:0,
                 from /home/wty/xstore-legacy/server/controler/../internal/table.hpp:4,
                 from /home/wty/xstore-legacy/server/controler/../internal/tables.hpp:3,
                 from /home/wty/xstore-legacy/server/controler/handlers.hpp:8,
                 from /home/wty/xstore-legacy/server/startup.hpp:8,
                 from /home/wty/xstore-legacy/server/worker.hpp:14,
                 from /home/wty/xstore-legacy/server/main.cc:6:
/home/wty/xstore-legacy/deps/mousika/rmi.h: In instantiation of ‘void RMINew<Weight_T>::finish_insert(bool) [with Weight_T = char]’:
/home/wty/xstore-legacy/deps/mousika/learned_index.h:101:5:   required from ‘void LearnedRangeIndexSingleKey<Val_T, Weight_T>::finish_insert(bool) [with Val_T = long unsigned int; Weight_T = char]’
/home/wty/xstore-legacy/src/smart_cache.hpp:252:5:   required from ‘void fstore::SCache<K, V, PAGE_TYPE, PAGEAlloc>::retrain(fstore::datastream::StreamIterator<unsigned int, PAGE_TYPE*>*, fstore::SCache<K, V, PAGE_TYPE, PAGEAlloc>::Tree&) [with K = long unsigned int; V = fstore::OpaqueData<8>; PAGE_TYPE = fstore::store::LeafNode<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager>; PAGEAlloc = fstore::BlockPager; fstore::SCache<K, V, PAGE_TYPE, PAGEAlloc>::Tree = fstore::store::NaiveTree<long unsigned int, fstore::OpaqueData<8>, fstore::BlockPager>]’
/home/wty/xstore-legacy/server/internal/learner.hpp:19:34:   required from here
/home/wty/xstore-legacy/deps/mousika/rmi.h:561:11: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘std::vector<double>::size_type {aka long unsigned int}’ [-Wformat=]
     printf("finish insert with: %u keys\n", all_keys.size());
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CMakeFiles/fserver.dir/build.make:62: recipe for target 'CMakeFiles/fserver.dir/server/main.cc.o' failed
make[3]: *** [CMakeFiles/fserver.dir/server/main.cc.o] Error 1
CMakeFiles/Makefile2:292: recipe for target 'CMakeFiles/fserver.dir/all' failed
make[2]: *** [CMakeFiles/fserver.dir/all] Error 2
CMakeFiles/Makefile2:304: recipe for target 'CMakeFiles/fserver.dir/rule' failed
make[1]: *** [CMakeFiles/fserver.dir/rule] Error 2
Makefile:253: recipe for target 'fserver' failed
make: *** [fserver] Error 2

**Comment by furtheranddeeper** [comment]
OK, now I get it.
#include <immintrin.h> should be added into xstore/src/stores/utils/rtm_scope.hpp
