### ISSUE TITLE
run ./fserver error with undefined symbol "omp_get_num_procs" in libmkl_intel_thread.so.1 

### ISSUE THREAD

**Issue by furtheranddeeper** [SJTU-IPADS/xstore#4]
After "make fserver" successfully, I try to run fserver.
But when I run fserver with "./fserver -db_type ycsb -model_config=ae_scripts/ycsb-model.toml", the terminal tells me that there is something wrong like below.
I have modified the "build-config.toml" , and make all successfully.

**modified in build-config.toml**
[externals]
mkl = { path = "/opt/intel/oneapi/mkl/latest", exports = ["mkl_rt"],lib = "lib/intel64",include="include"}

**run fserver error**
./fserver -db_type ycsb -model_config=ae_scripts/ycsb-model.toml
[main.cc:257] use configuration: Server config:
        using memory for leaf nodes: 20.0000 GB;
        allocated RDMA heap size: 8.0000 GB;
        server communication type: ud.
 of config file: server/config.toml
[memory_util.hpp:37] huge page alloc failed!
[memory_util.hpp:45] use default malloc for allocating page
[main.cc:271] use page mem: 21474836480
[allocator_master.hpp:50] allocator master register memory: 8587836416
[main.cc:277] Memory layout of the server: | meta 0x0:0x0+2MB | page 0x200000:0x200000+20GB | Heap 0x500200400:0x500200400+7.99805GB |
[main.cc:305] server wait for threads to join ...
[main.cc:307] Start populating DB: ycsb with num: 10000
[main.cc:167] B+tree load done, leaf sz: 384 rdma base: 140674674454544
[main.cc:183] start training!
[model_config.hpp:29] load second stage num: 2
[mod.hh:45] init XCache using 100000 sub models
[worker.hpp:98] Server: 0 use nic id: 1
./fserver: symbol lookup error: /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_intel_thread.so.1: undefined symbol: omp_get_num_procs

**"ldd fserver" to find if the libmkl path is right**
libmkl_rt.so.1 => /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_rt.so.1 (0x00007ff6527d9000)
**"nm -D /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_rt.so.1" find  that omp_get_num_procs is actually undefined** 
0000000002b27580 T mkl_vsl_serv_threader_sections
                 U omp_get_max_threads
                 U omp_get_nested
                 **U omp_get_num_procs**
                 U omp_get_num_threads
                 U omp_get_thread_num
                 U omp_in_parallel
                 U omp_set_nested
                 U pthread_getspecific
                 U pthread_key_create
                 U pthread_key_delete
                 U pthread_setspecific
                 U sin

**Comment by furtheranddeeper** [comment]
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/wty/xstore-legacy/deps/boost/lib:/opt/intel/oneapi/compiler/2022.1.0/linux/compiler/lib/ia32_lin:/opt/intel/oneapi/compiler/2022.1.0/linux/compiler/lib/intel64_lin
libboost.so and libiomp5.so should be added

**Comment by Tyler-ytr** [comment]
这部分可以添加到toml的cmd里面；比如:
````
[[pass]]
host = "server10.lab427.com"
path = "~/worker/my_xstore"
cmd = ". /opt/intel/oneapi/mkl/latest/env/vars.sh intel64 mod&&export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/tyleryin/worker/xstore/deps/boost/lib&&./fserver --help"
````
因为在,bashrc或者.zshrc里面的环境变量修改不会影响python的cmd调用
