### ISSUE TITLE
I cannot run ycsbd workload with the command written in the ycsbd.toml

### ISSUE THREAD

**Issue by furtheranddeeper** [SJTU-IPADS/xstore#5]
Sorry,it is still me...
I have one machine for server and one machine for client. They are connected well with RoCE.
I run ycsbc and ycsba successfully. However when I try to run ycsbd, the client cannot response.
Because of something wrong in SSH when running bootstrap.py, I just use the commands in ycsbd.toml to reproduce. 
Do the commands be used in the right way?
./fserver --threads 24 --id 0 -ycsb_num=20000 -db_type dummy -ycsb_num 20000000 --model_config=ae_scripts/ycsb-dynamic-model.toml
./micro --threads 24 -concurrency 1 -workloads dynamic2 -server_host 192.168.0.4 -id 1 -total_accts=10000000 -need_hash=true
client terminal prints below , after which prints nothing at all 
----------------------------------------------------------------------------------
[mem_region.hpp:68] region manager alloc memory: 0x7fcecb3ff010
[allocator_master.hpp:50] allocator master register memory: 2147483648
[allocator_master.hpp:43] AllocatorMaster<0> inited multiple times
[dynamic_expan.hh:23] client use dynamic changing workloads, V4
[main.cc:295] starting 24 threads, using workload: dynamic2
[main.cc:299] all threads start done
[controler.hpp:28] micro controler main loop starts
[rdma_ctrl.hpp:110] rdma ctrl started!
[controler.hpp:40] memory regsiter done 75
[lib.hpp:43] fetch mr done
[lib.hpp:50] create ud done
[controler.hpp:47] controler adapter done
[controler.hpp:143] Micro controler starts.

**Comment by wxdwfc** [comment]
Do you apply the `global_config` listed at the top of the run script? e.g., `global_configs="--uniform=true --total_accts=20000000 --model_update_gap=1 --get_ratio=95 --server_host=val10 --workloads=dynamic --thr\
eads=24 --force_rpc=false --concurrency=4 --undefok=concurrency,force_rpc,threads,workloads,server_host,get_ratio,model_update_gap,tota\
l_accts,uniform"`

It will overwrites the conflicting parts of the specific configurations.

**Comment by furtheranddeeper** [comment]
**I tried to run ./micro with global_config listed at the top of the run script(./ae_scripts/ycsbd.toml)
It seems that micro assertion failed when executing [dynamic_v4.hh:170] eg. ASSERT(qp != nullptr);
I have met the problem when I use error command to run ycsbc, does the commands below is still wrong?
./fserver --threads 24 --id 0 -ycsb_num=20000 -db_type dummy -ycsb_num 20000000 --model_config=ae_scripts/ycsb-dynamic-model.toml
./micro --uniform=true --total_accts=20000000 --model_update_gap=1 --get_ratio=95 --server_host=192.168.0.4 --workloads=dynamic --threads=24 --force_rpc=false --concurrency=4 --undefok=concurrency,force_rpc,threads,workloads,server_host,get_ratio,model_update_gap,total_accts,uniform**

./micro prints
[mem_region.hpp:68] region manager alloc memory: 0x7f10be3ff010
[allocator_master.hpp:50] allocator master register memory: 2147483648
[allocator_master.hpp:43] AllocatorMaster<0> inited multiple times
[dynamic_v4.hh:23] client use dynamic changing workloads, V4
[main.cc:295] starting 24 threads, using workload: dynamic
[main.cc:299] all threads start done
[controler.hpp:28] micro controler main loop starts
[rdma_ctrl.hpp:110] rdma ctrl started!
[controler.hpp:40] memory regsiter done 75
[lib.hpp:43] fetch mr done
[lib.hpp:50] create ud done
[controler.hpp:47] controler adapter done
[controler.hpp:143] Micro controler starts.
[dynamic_v4.hh:170] Assertion!
[dynamic_v4.hh:170] Assertion!
m[dynamic_v4.hh:170] Assertion!
Aborted (core dumped)

**Comment by wxdwfc** [comment]
The error states that the client failed to connect the QP with the server. It seems that the parameters are correct, but maybe tuned for different platforms.

**Comment by furtheranddeeper** [comment]
It seems that client should wait for server to prepare qp and some other resources.
