### ISSUE TITLE
[ud_msg.cc:43] Assertion! when running ycsbc

### ISSUE THREAD

**Issue by furtheranddeeper** [SJTU-IPADS/xstore#6]
I reproduce the experiment(XStore-legacy) at two different machines because of some accidents happened.
After well compiled, something went wrong while running ycsbc workload.
[ud_msg.cc:43] Assertion! 
Ycsb client meets assertion when create ah, while never happens before.
Should I modify something at the new two machines?
----------------------------------------------------------------------------------------------------------------------------------------
./ycsb -workloads ycsbc -server_host 192.168.0.3 --id 1 -total_accts=1000000 --use_master=false --eval_type=sc --threads 1
[mem_region.hpp:68] region manager alloc memory: 0x7fe284fff010
[allocator_master.hpp:50] allocator master register memory: 2147483648
[allocator_master.hpp:43] AllocatorMaster<0> inited multiple times
[main.cc:131] starting threads, using workload: ycsbc
[main.cc:137] wait for thread to be ready
[rdma_ctrl.hpp:110] rdma ctrl started!
[ud_msg.cc:43] Assertion!
Aborted (core dumped)

ud_msg.cc:43
auto ah = create_ah(qp_, fetched_attr);
    if (ah == nullptr)
    {
      ASSERT(false);
      return ERR;
    }
static ibv_ah *create_ah(UDQP *qp, const QPAttr &attr)
{
  struct ibv_ah_attr ah_attr;
  ah_attr.is_global = 1;
  ah_attr.dlid = attr.lid;
  ah_attr.sl = 0;
  ah_attr.src_path_bits = 0;
  ah_attr.port_num = attr.port_id;

  ah_attr.grh.dgid.global.subnet_prefix = attr.addr.subnet_prefix;
  ah_attr.grh.dgid.global.interface_id = attr.addr.interface_id;
  ah_attr.grh.flow_label = 0;
  ah_attr.grh.hop_limit = 255;
  ah_attr.grh.sgid_index = qp->rnic_p->addr.local_id;
  return ibv_create_ah(qp->rnic_p->pd, &ah_attr);
}

**Comment by baotonglu** [comment]
Hi bro, I am also facing some difficulties in running the code. Could you leave your contact details? Maybe we could have a discussion.

**Comment by wxdwfc** [comment]
Hi, you can post the problems here, or can contact me at wxdwfc@gmail.com.

**Comment by furtheranddeeper** [comment]
ud_msg.cc may need specified ofed version.
I changed driver version to ofed 5.1, and the programs ran well.
